SELECT * FROM "GROUP";

INSERT INTO "GROUP" VALUES(SEQ_GROUP_NO.NEXTVAL, 1, '근육빵빵', DEFAULT, NULL, '근육맨이되는 그날까지', 'Y', 0);
INSERT INTO "GROUP" VALUES(SEQ_GROUP_NO.NEXTVAL, 2, '손으로 사부작', DEFAULT, NULL, '손으로 만드는건 다한다', 'Y', 0);
INSERT INTO "GROUP" VALUES(SEQ_GROUP_NO.NEXTVAL, 3, '롤링롤링', DEFAULT, NULL, '브론즈 미만잡 안받아요', 'Y', 0);
INSERT INTO "GROUP" VALUES(SEQ_GROUP_NO.NEXTVAL, 4, '보라빛향기', DEFAULT, NULL, '진, 뷔, 제이홉, 슈가, 정국, RM, 지민 영원히 보라보라해', 'Y', 0);
INSERT INTO "GROUP" VALUES(SEQ_GROUP_NO.NEXTVAL, 5, '위아리스트베이비', DEFAULT, NULL, '모든 아티스트들 환영합니다', 'Y', 0);
INSERT INTO "GROUP" VALUES(SEQ_GROUP_NO.NEXTVAL, 6,'', DEFAULT, NULL, '', 'Y', 0);
INSERT INTO "GROUP" VALUES(SEQ_GROUP_NO.NEXTVAL, 7,'', DEFAULT, NULL, '', 'Y', 0);
INSERT INTO "GROUP" VALUES(SEQ_GROUP_NO.NEXTVAL, 8,'', DEFAULT, NULL, '', 'Y', 0);
INSERT INTO "GROUP" VALUES(SEQ_GROUP_NO.NEXTVAL, 9,'', DEFAULT, NULL, '', 'Y', 0);
INSERT INTO "GROUP" VALUES(SEQ_GROUP_NO.NEXTVAL, 10,'', DEFAULT, NULL, '', 'Y', 0);

UPDATE "GROUP" SET TOPIC_CODE=12 WHERE GROUP_NO =1;

COMMIT;