-- 본드 샘플 데이터 생
SELECT * FROM "GROUP";

INSERT INTO "GROUP" VALUES(SEQ_GROUP_NO.NEXTVAL, 1, '근육빵빵', DEFAULT,'근육맨이되는 그날까지', 'Y', 0);
INSERT INTO "GROUP" VALUES(SEQ_GROUP_NO.NEXTVAL, 2, '손으로 사부작', DEFAULT,'손으로 만드는건 다한다', 'Y', 0);
INSERT INTO "GROUP" VALUES(SEQ_GROUP_NO.NEXTVAL, 3, '롤링롤링', DEFAULT,'브론즈 미만잡 안받아요', 'Y', 0);
INSERT INTO "GROUP" VALUES(SEQ_GROUP_NO.NEXTVAL, 4, '보라빛향기', DEFAULT,'진, 뷔, 제이홉, 슈가, 정국, RM, 지민 영원히 보라보라해', 'Y', 0);
INSERT INTO "GROUP" VALUES(SEQ_GROUP_NO.NEXTVAL, 5, '위아리스트베이비', DEFAULT,'모든 아티스트들 환영합니다', 'Y', 0);
INSERT INTO "GROUP" VALUES(SEQ_GROUP_NO.NEXTVAL, 6, '내고향 6시', DEFAULT,'아침 6시 일어나 개밥줘 소밥줘 할머니 밥 차려드려 깨밭에 가서 깨 털어', 'Y', 0);
INSERT INTO "GROUP" VALUES(SEQ_GROUP_NO.NEXTVAL, 7, '불멍타임', DEFAULT,'캠핑을 사랑하는 사람 모두 환영합니다', 'Y', 0);
INSERT INTO "GROUP" VALUES(SEQ_GROUP_NO.NEXTVAL, 8, '집밥 선생', DEFAULT,'우리집에서는 내가 백선생 슈가러버', 'Y', 0);
INSERT INTO "GROUP" VALUES(SEQ_GROUP_NO.NEXTVAL, 9, '씨드머니 급구', DEFAULT,'월급쟁이를 벗어나고 싶은 투자자들 모여라', 'Y', 0);
INSERT INTO "GROUP" VALUES(SEQ_GROUP_NO.NEXTVAL, 10, '포토마니아', DEFAULT,'인물, 자연, 음식 등 모든 것을 사진으로 남기세요', 'Y', 0);
INSERT INTO "GROUP" VALUES(SEQ_GROUP_NO.NEXTVAL, 11, '내 방 꼬라지', DEFAULT,'내 방 셀프 인테리어는 내가 한다', 'Y', 0);
INSERT INTO "GROUP" VALUES(SEQ_GROUP_NO.NEXTVAL, 12, '개발새발', DEFAULT,'개발새발이지만 타이핑은 할 줄 알아요. 영타 100은 나와야 가입 가능', 'Y', 0);

UPDATE "GROUP" SET TOPIC_CODE=12 WHERE GROUP_NO =1;

COMMIT;

-- 내가 가입한 본드 조회
SELECT * FROM MEMBER_JOIN;
SELECT * FROM MEMBER;

INSERT INTO "MEMBER_JOIN" VALUES(SEQ_MEMBER_JOIN_NO.NEXTVAL, 2, 1, 'N', DEFAULT, 0, NULL);
INSERT INTO "MEMBER_JOIN" VALUES(SEQ_MEMBER_JOIN_NO.NEXTVAL, 3, 1, 'N', DEFAULT, 0, NULL);
INSERT INTO "MEMBER_JOIN" VALUES(SEQ_MEMBER_JOIN_NO.NEXTVAL, 4, 1, 'N', DEFAULT, 0, NULL);
INSERT INTO "MEMBER_JOIN" VALUES(SEQ_MEMBER_JOIN_NO.NEXTVAL, 5, 1, 'N', DEFAULT, 0, NULL);
INSERT INTO "MEMBER_JOIN" VALUES(SEQ_MEMBER_JOIN_NO.NEXTVAL, 6, 1, 'N', DEFAULT, 0, NULL);
INSERT INTO "MEMBER_JOIN" VALUES(SEQ_MEMBER_JOIN_NO.NEXTVAL, 1, 2, 'N', DEFAULT, 0, NULL);
INSERT INTO "MEMBER_JOIN" VALUES(SEQ_MEMBER_JOIN_NO.NEXTVAL, 1, 3, 'N', DEFAULT, 0, NULL);

-- 내 그룹 조회
SELECT G.GROUP_NO, GROUP_NAME, 
	(SELECT COUNT(*) FROM MEMBER_JOIN M
	WHERE M.GROUP_NO = G.GROUP_NO) MEMBER_COUNT,
	(SELECT GROUP_IMG_PATH || GROUP_IMG_RENAME FROM GROUP_IMG GI
	WHERE GI.GROUP_NO = G.GROUP_NO) GROUP_IMG
FROM "GROUP" G
JOIN MEMBER_JOIN M ON(M.GROUP_NO = G.GROUP_NO)
WHERE MEMBER_NO = 1
AND GROUP_STATUS = 0;

SELECT * FROM "GROUP";
SELECT * FROM GROUP_IMG;

SELECT COUNT(MEMBER_NO) FROM MEMBER_JOIN
WHERE GROUP_NO = 1;

-- 그룹 정보 조회
SELECT GROUP_NO, GROUP_NAME, GROUP_COMMENT,
	(SELECT COUNT(MEMBER_NO) FROM MEMBER_JOIN M
	WHERE M.GROUP_NO = G.GROUP_NO) MEMBER_COUNT,
	(SELECT GROUP_IMG_PATH || GROUP_IMG_RENAME FROM GROUP_IMG GI
	WHERE GI.GROUP_NO = G.GROUP_NO) GROUP_IMG
FROM "GROUP" G
WHERE GROUP_NO = 1;

-- INSERT INTO 이미지테이블 VALUES(이미지번호, 이미지경로, 이미지리네임, 이미지오리지널, 이미지순서, 게시판번호)
INSERT INTO GROUP_IMG VALUES(SEQ_GROUP_IMG_NO.NEXTVAL, 1, 'coding.jpg','20221118105843_00001.jpg', '/resources/images/bond/profile/');
INSERT INTO GROUP_IMG VALUES(SEQ_GROUP_IMG_NO.NEXTVAL, 3, 'health.jpeg','20221118105843_00002.jpg', '/resources/images/bond/profile/');
INSERT INTO GROUP_IMG VALUES(SEQ_GROUP_IMG_NO.NEXTVAL, 그룹번호, 원본, 리네임, 경로)

INSERT INTO BOARD_IMG
VALUES(SEQ_IMG_NO.NEXTVAL, '/resources/images/board/',
'20221116105843_00002.gif', '2.gif', 1 , 1998);

COMMIT;

SELECT * FROM MEMBER_IMG;
SELECT * FROM GROUP_IMG WHERE GROUP_NO = 16;

SELECT * FROM "GROUP";
SELECT * FROM "GROUP_TOPIC";


INSERT INTO "GROUP" VALUES(SEQ_GROUP_NO.NEXTVAL, 1, '따르릉따르릉', DEFAULT, '자전거 동호회입니다. 따릉이도 환영해요. 허벅지 근육 득근합시다.', 'Y', 0);


SELECT * FROM MEMBER_JOIN;


INSERT INTO "MEMBER_JOIN" VALUES(SEQ_MEMBER_JOIN_NO.NEXTVAL, 15, 6, DEFAULT, DEFAULT, DEFAULT, NULL);
INSERT INTO "MEMBER_JOIN" VALUES(SEQ_MEMBER_JOIN_NO.NEXTVAL, 그룹번호, 멤버번호, 'Y', DEFAULT, 0, NULL);
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL, 1, 2,'집에보내줘', 0, 'Y', DEFAULT, DEFAULT, 'N', 'N');

SELECT * FROM POST WHERE GROUP_NO = 1;
SELECT * FROM POST_LIKE;

SELECT * FROM REPLY;

INSERT INTO POST_LIKE VALUES(485, 2);
INSERT INTO POST_LIKE VALUES(485, 3);
INSERT INTO POST_LIKE VALUES(485, 4);
INSERT INTO POST_LIKE VALUES(485, 5);

DELETE FROM POST_LIKE WHERE POST_NO = 500;

COMMIT;
ROLLBACK;

DELETE FROM REPLY WHERE REPLY_NO = 12;

-- 댓글 샘플 데이터
INSERT INTO "REPLY" VALUES(SEQ_REPLY_NO.NEXTVAL, 485, 2,'부모 댓글1', DEFAULT, DEFAULT, null);
INSERT INTO "REPLY" VALUES(SEQ_REPLY_NO.NEXTVAL, 485, 3,'부모 댓글2', DEFAULT, DEFAULT, null);
INSERT INTO "REPLY" VALUES(SEQ_REPLY_NO.NEXTVAL, 485, 4,'대댓글1', DEFAULT, DEFAULT, 8);
INSERT INTO "REPLY" VALUES(SEQ_REPLY_NO.NEXTVAL, 485, 5,'대댓글2', DEFAULT, DEFAULT, 8);
INSERT INTO "REPLY" VALUES(SEQ_REPLY_NO.NEXTVAL, 485, 6,'대댓글3', DEFAULT, DEFAULT, 9);

INSERT INTO "REPLY" VALUES(SEQ_REPLY_NO.NEXTVAL, 500,'대댓글4', DEFAULT, DEFAULT,1998 ,10, 2003);
INSERT INTO "REPLY" VALUES(SEQ_REPLY_NO.NEXTVAL, 500,'대댓글5', DEFAULT, DEFAULT,1998 ,1, 2003);


-- 게시글 목록조회
SELECT POST_NO, MEMBER_NAME, POST_CONTENT, POST_VIEW, 
	CASE  
      WHEN SYSDATE - POST_DATE < 1/24/60
      THEN FLOOR( (SYSDATE - POST_DATE) * 24 * 60 * 60 ) || '초 전'
      WHEN SYSDATE - POST_DATE < 1/24
      THEN FLOOR( (SYSDATE - POST_DATE) * 24 * 60) || '분 전'
      WHEN SYSDATE - POST_DATE < 1
      THEN FLOOR( (SYSDATE - POST_DATE) * 24) || '시간 전'
      ELSE TO_CHAR(POST_DATE, 'YYYY"년" MM"월" DD"일" HH24:MI')
   END POST_DATE,
	CASE  
      WHEN SYSDATE - EDIT_DATE < 1/24/60
      THEN FLOOR( (SYSDATE - EDIT_DATE) * 24 * 60 * 60 ) || '초 전'
      WHEN SYSDATE - EDIT_DATE < 1/24
      THEN FLOOR( (SYSDATE - EDIT_DATE) * 24 * 60) || '분 전'
      WHEN SYSDATE - EDIT_DATE < 1
      THEN FLOOR( (SYSDATE - EDIT_DATE) * 24) || '시간 전'
      ELSE TO_CHAR(EDIT_DATE, 'YYYY-MM-DD')
   END EDIT_DATE,
   (SELECT COUNT(*) FROM REPLY R
	WHERE R.POST_NO = P.POST_NO) REPLY_COUNT,
	(SELECT COUNT(*) FROM POST_LIKE L
	WHERE L.POST_NO = P.POST_NO) LIKE_COUNT,
	(SELECT MEMBER_IMG_PATH || MEMBER_IMG_RENAME 
	FROM MEMBER_IMG MI
	WHERE MI.MEMBER_NO = P.MEMBER_NO) MEMBER_IMG
FROM POST P
JOIN MEMBER M ON(P.MEMBER_NO = M.MEMBER_NO)
WHERE POST_NO = 143
AND POST_DEL_YN = 'N'
ORDER BY POST_NO DESC;




-- 게시글 상세조회
SELECT POST_NO, MEMBER_NAME, POST_CONTENT, POST_VIEW, P.MEMBER_NO,
	TO_CHAR(POST_DATE, 'YYYY"년" MM"월" DD"일" HH24:MI:SS') POST_DATE,
	TO_CHAR(EDIT_DATE, 'YYYY"년" MM"월" DD"일" HH24:MI:SS') EDIT_DATE,
	(SELECT COUNT(*) FROM REPLY R
	WHERE R.POST_NO = P.POST_NO) REPLY_COUNT,
	(SELECT COUNT(*) FROM POST_LIKE L
	WHERE L.POST_NO = P.POST_NO) LIKE_COUNT,
	(SELECT MEMBER_IMG_PATH || MEMBER_IMG_RENAME 
	FROM MEMBER_IMG MI
	WHERE MI.MEMBER_NO = P.MEMBER_NO) MEMBER_IMG
FROM POST P
JOIN MEMBER M ON(P.MEMBER_NO = M.MEMBER_NO)
WHERE POST_NO = 143
AND POST_DEL_YN = 'N';


-- 댓글 수
SELECT COUNT(*) FROM "COMMENT"
WHERE BOARD_NO = 1995;

-- 좋아요 수
SELECT COUNT(*) FROM BOARD_LIKE L
WHERE L.BOARD_NO = 1998;

SELECT COUNT(*) FROM POST_LIKE
WHERE POST_NO = 485
AND MEMBER_NO = 2;

-- 게시글 삽입
SELECT * FROM POST ORDER BY POST_NO DESC;

INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL, 1, 3, '집에보내줘', NULL, DEFAULT, DEFAULT, NULL, DEFAULT, DEFAULT);
UPDATE POST SET POST_CONTENT = '수정한내용' WHERE POST_NO = 10;

SELECT * FROM POST WHERE POST_NO=547;

DELETE FROM POST_IMG WHERE POST_NO=554;
ROLLBACK;

SELECT * FROM  POST_IMG;

SELECT IMG_NO, POST_NO, (IMG_PATH || IMG_RENAME) POST_IMG
FROM POST_IMG
JOIN POST USING(POST_NO)
WHERE GROUP_NO = 1
ORDER BY POST_NO ;

SELECT (IMG_PATH || IMG_RENAME) POST_IMG, PI.POST_NO, MEMBER_NAME,
	(SELECT MEMBER_IMG_PATH || MEMBER_IMG_RENAME 
	FROM MEMBER_IMG MI
	WHERE MI.MEMBER_NO = M.MEMBER_NO) MEMBER_IMG
FROM POST_IMG PI
JOIN POST P ON(P.POST_NO = PI.POST_NO)
JOIN "MEMBER" M ON(M.MEMBER_NO = P.MEMBER_NO)
WHERE IMG_NO=30;

SELECT * FROM REPLY WHERE POST_NO = 550;

SELECT * FROM POST_IMG;

ALTER TABLE POST_IMG DROP COLUMN IMG_ORDER;

-- INSERT INTO POST_IMG VALUES(SEQ_IMG_NO.NEXTVAL, #{postNo}, #{imgRename}, #{imagePath})

SELECT * FROM POST_LIKE;


SELECT POST_NO, MEMBER_NAME, POST_CONTENT, P.MEMBER_NO,
	TO_CHAR(POST_DATE, 'YYYY"년" MM"월" DD"일" HH24:MI:SS') POST_DATE,
	TO_CHAR(EDIT_DATE, 'YYYY"년" MM"월" DD"일" HH24:MI:SS') EDIT_DATE,
	(SELECT COUNT(*) FROM REPLY R
	WHERE R.POST_NO = P.POST_NO) REPLY_COUNT,
	(SELECT COUNT(*) FROM POST_LIKE L
	WHERE L.POST_NO = P.POST_NO) LIKE_COUNT,
	(SELECT COUNT(*) FROM POST_VIEW V
	WHERE V.POST_NO = P.POST_NO)POST_VIEW,
	(SELECT MEMBER_IMG_PATH || MEMBER_IMG_RENAME 
	FROM MEMBER_IMG MI
	WHERE MI.MEMBER_NO = P.MEMBER_NO) MEMBER_IMG
FROM POST P
JOIN MEMBER M ON(P.MEMBER_NO = M.MEMBER_NO)
WHERE POST_NO = 542
AND POST_DEL_YN = 'N'

SELECT COUNT(*)
FROM POST_VIEW
WHERE POST_NO = 530
AND MEMBER_NO = 2;

SELECT POST_CONTENT FROM POST WHERE POST_NO = 500;

SELECT * FROM POST_VIEW;

INSERT INTO POST_VIEW VALUES(530, 2);


SELECT LEVEL, C.* FROM
	(SELECT REPLY_NO, REPLY_CONTENT, 
		TO_CHAR(REPLY_DATE, 'YYYY"년" MM"월" DD"일" HH24"시" MI"분" SS"초"') REPLY_DATE,
		POST_NO, R.MEMBER_NO, MEMBER_NAME,
		(SELECT MEMBER_IMG_PATH || MEMBER_IMG_RENAME 
		FROM MEMBER_IMG MI
		WHERE MI.MEMBER_NO = R.MEMBER_NO) MEMBER_IMG,
		PARENT_NO, REPLY_DEL_YN
	FROM REPLY R
	JOIN MEMBER M ON(R.MEMBER_NO = M.MEMBER_NO)
	WHERE POST_NO = 544
	AND REPLY_DEL_YN='N') C
START WITH PARENT_NO IS NULL
CONNECT BY PRIOR REPLY_NO = PARENT_NO
ORDER SIBLINGS BY REPLY_NO;
ROLLBACK;
SELECT * FROM POST WHERE POST_NO = 80;
SELECT * FROM POST WHERE POST_DEL_YN  = 'Y';
UPDATE POST SET POST_DEL_YN ='Y' WHERE POST_NO=80;
SELECT * FROM REPLY;
SELECT * FROM MEMBER;
SELECT * FROM MEMBER_JOIN WHERE GROUP_NO=4;

INSERT INTO "REPLY" VALUES(SEQ_REPLY_NO.NEXTVAL, 544, 2,'마이클 나대지마', DEFAULT, DEFAULT, null);
INSERT INTO "REPLY" VALUES(SEQ_REPLY_NO.NEXTVAL, 544, 3,'마이클 절대지켜', DEFAULT, DEFAULT, null);
INSERT INTO "REPLY" VALUES(SEQ_REPLY_NO.NEXTVAL, 544, 4,'말넘심', DEFAULT, DEFAULT, 16);
INSERT INTO "REPLY" VALUES(SEQ_REPLY_NO.NEXTVAL, 544, 5,'동의', DEFAULT, DEFAULT, 16);
INSERT INTO "REPLY" VALUES(SEQ_REPLY_NO.NEXTVAL, 544, 6,'마이클 엄마임?', DEFAULT, DEFAULT, 17);

INSERT INTO "REPLY" VALUES(SEQ_REPLY_NO.NEXTVAL, #{postNo}, #{memberNo}, #{replyContent}, DEFAULT, DEFAULT, NULL);

UPDATE "REPLY" SET
REPLY_DEL_YN = 'Y',
REPLY_CONTENT = '삭제된 댓글입니다.'
WHERE REPLY_NO = 3;

SELECT * FROM "GROUP" WHERE GROUP_NO = 23;

SELECT * FROM "MEMBER";

SELECT * FROM MEMBER_JOIN M
WHERE GROUP_NO = 4;

SELECT * FROM MEMBER;
SELECT * FROM MEMBER WHERE MEMBER_NO =8;
SELECT * FROM MEMBER WHERE MEMBER_NO =34;
SELECT * FROM MEMBER_JOIN WHERE GROUP_NO=23;